"use client";
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '../lib/supabase/client';
import './globals.css';

const days=['Senin','Selasa','Rabu','Kamis','Jumat'];
const seed=[['Senin','07.10','09.40','Bisnis Global'],['Senin','09.40','12.10','Business Creativity and Innovation'],['Selasa','07.10','09.40','Metodologi Penelitian'],['Selasa','09.40','12.10','Analisis Risiko Bisnis'],['Rabu','07.10','09.40','Operation and Supply Chain Management'],['Rabu','09.40','12.10','Manajemen Bisnis Mikro dan Kecil'],['Kamis','07.10','09.40','Desain Program Pendidikan dan Pelatihan'],['Kamis','12.10','14.40','Startup Entrepreneur']];
const courseNames=[...new Set(seed.map(x=>x[3]))];
function dname(d){return new Intl.DateTimeFormat('id-ID',{weekday:'long'}).format(d)} function fd(v){return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}
function urgency(v,status){if(status==='Selesai')return ['Selesai','done'];const diff=new Date(v)-new Date();if(diff<0)return ['Terlambat','late'];if(diff<86400000)return ['Hari ini','today'];if(diff<259200000)return ['Mendekati deadline','soon'];return ['Aman','safe']}
export default function App(){const supabase=createClient();const [user,setUser]=useState(null),[profile,setProfile]=useState(null),[page,setPage]=useState('Dashboard'),[courses,setCourses]=useState([]),[schedule,setSchedule]=useState([]),[tasks,setTasks]=useState([]),[progress,setProgress]=useState([]),[selected,setSelected]=useState(null),[showTask,setShowTask]=useState(false),[showSchedule,setShowSchedule]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{let active=true;(async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){location.href='/login';return}const [{data:p},{data:c},{data:s},{data:t},{data:pr}]=await Promise.all([supabase.from('profiles').select('*').eq('id',user.id).single(),supabase.from('courses').select('*').order('name'),supabase.from('schedules').select('*, courses(name)').order('day').order('start_time'),supabase.from('tasks').select('*, courses(name), task_attachments(*)').order('deadline'),supabase.from('task_progress').select('*').eq('user_id',user.id)]);if(active){setUser(user);setProfile(p);setCourses(c||[]);setSchedule(s||[]);setTasks(t||[]);setProgress(pr||[]);setLoading(false)}})();return()=>{active=false}},[]);
 const isAdmin=profile?.role==='admin'; const today=dname(new Date()); const todaySchedule=schedule.filter(s=>s.day===today); const mine=tasks.map(t=>({...t, mine:progress.find(p=>p.task_id===t.id)||{status:'Belum mulai',progress:0,notes:''}})); const unfinished=mine.filter(t=>t.mine.status!=='Selesai'); const nearest=unfinished.sort((a,b)=>new Date(a.deadline)-new Date(b.deadline)).slice(0,5);
 async function signout(){await supabase.auth.signOut();location.href='/login'} async function updateProgress(task,patch){const current=task.mine;const next={user_id:user.id,task_id:task.id,status:patch.status??current.status,progress:patch.progress??current.progress,notes:patch.notes??current.notes};const {data,error}=await supabase.from('task_progress').upsert(next,{onConflict:'user_id,task_id'}).select().single();if(!error)setProgress(x=>[...x.filter(p=>p.task_id!==task.id),data])}
 async function saveTask(e){e.preventDefault();const f=new FormData(e.currentTarget);let task={course_id:f.get('course_id'),title:f.get('title'),description:f.get('description'),deadline:f.get('deadline'),priority:f.get('priority'),submission_url:f.get('submission_url')||null};const {data,error}=await supabase.from('tasks').insert(task).select('*,courses(name)').single();if(error){alert(error.message);return}const files=[...f.getAll('images')].filter(x=>x instanceof File&&x.size);for(const file of files){const path=`${data.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await supabase.storage.from('task-instructions').upload(path,file,{contentType:file.type});if(!up.error)await supabase.from('task_attachments').insert({task_id:data.id,path,file_name:file.name,mime_type:file.type})}const {data:nt}=await supabase.from('tasks').select('*, courses(name), task_attachments(*)').eq('id',data.id).single();setTasks(x=>[...x,nt]);setShowTask(false);e.currentTarget.reset()}
 async function saveSchedule(e){e.preventDefault();const f=new FormData(e.currentTarget);const {data,error}=await supabase.from('schedules').insert({course_id:f.get('course_id'),day:f.get('day'),start_time:f.get('start_time'),end_time:f.get('end_time'),room:f.get('room')||null,lecturer:f.get('lecturer')||null}).select('*,courses(name)').single();if(error)alert(error.message);else{setSchedule(x=>[...x,data]);setShowSchedule(false)}}
 if(loading)return <div className="loading">Memuat Academic Hub…</div>;
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><div><strong>Academic Hub</strong><span>B24</span></div></div><nav>{['Dashboard','Jadwal','Tugas','Kalender','Mata Kuliah',...(isAdmin?['Admin']:[])].map(x=><button className={page===x?'nav active':'nav'} onClick={()=>setPage(x)} key={x}>{x}</button>)}</nav><div className="sidebar-bottom"><button className="nav" onClick={signout}>↪ Keluar</button><div className="profile"><div className="avatar">{(profile?.full_name||user.email).slice(0,2).toUpperCase()}</div><div><strong>{profile?.full_name||'Mahasiswa'}</strong><span>{isAdmin?'Administrator':'Mahasiswa'}</span></div></div></div></aside><section className="content"><header className="topbar"><div><div className="eyebrow">{page}</div><h1>{page==='Dashboard'?'Selamat datang kembali 👋':page}</h1></div>{isAdmin&&<div className="admin-pill">ADMIN</div>}</header>
 {page==='Dashboard'&&<Dashboard today={today} todaySchedule={todaySchedule} nearest={nearest} mine={mine} onOpen={setSelected} />}
 {page==='Jadwal'&&<Schedule schedule={schedule} admin={isAdmin} onAdd={()=>setShowSchedule(true)} />}
 {page==='Tugas'&&<Tasks tasks={mine} onOpen={setSelected} />}
 {page==='Kalender'&&<Calendar tasks={mine} schedule={schedule}/>} {page==='Mata Kuliah'&&<Courses courses={courses} tasks={mine} schedule={schedule} onOpen={setSelected}/>} {page==='Admin'&&isAdmin&&<Admin courses={courses} tasks={tasks} schedule={schedule} onTask={()=>setShowTask(true)} onSchedule={()=>setShowSchedule(true)} />}</section>
 {selected&&<TaskDetail task={selected} mine={selected.mine} admin={isAdmin} onClose={()=>setSelected(null)} update={p=>updateProgress(selected,p)} />}
 {showTask&&isAdmin&&<TaskForm courses={courses} onClose={()=>setShowTask(false)} onSave={saveTask}/>} {showSchedule&&isAdmin&&<ScheduleForm courses={courses} onClose={()=>setShowSchedule(false)} onSave={saveSchedule}/>}</main>}
function Dashboard({today,todaySchedule,nearest,mine,onOpen}){return <div className="page-grid"><section className="hero"><div><div className="hero-date">{fd(new Date())}</div><h2>Fokus pada hal yang paling penting hari ini.</h2><p>{today} · {todaySchedule.length?`${todaySchedule.length} kelas hari ini`:'Tidak ada kelas hari ini'}</p></div><div className="hero-day">{today.slice(0,3).toUpperCase()}</div></section><section className="stats"><Stat n={mine.filter(t=>t.mine.status!=='Selesai').length} l="Belum selesai"/><Stat n={mine.filter(t=>t.mine.status==='Sedang dikerjakan').length} l="Sedang dikerjakan"/><Stat n={mine.filter(t=>t.mine.status==='Selesai').length} l="Selesai"/><Stat n={mine.filter(t=>urgency(t.deadline,t.mine.status)[1]==='late').length} l="Terlambat"/></section><div className="two-panels"><section className="panel"><PanelTitle t="Jadwal hari ini" a="Lihat jadwal"/>{todaySchedule.length?todaySchedule.map(s=><div className="schedule-row" key={s.id}><div className="time">{s.start_time}<span>{s.end_time}</span></div><div><strong>{s.courses?.name}</strong><span>{s.room||'Ruangan belum diisi'}</span></div></div>):<Empty t="Tidak ada kelas hari ini."/>}</section><section className="panel"><PanelTitle t="Deadline terdekat" a="Prioritas"/>{nearest.map(t=><TaskRow key={t.id} t={t} open={()=>onOpen(t)}/>)}</section></div></div>}
function Schedule({schedule,admin,onAdd}){return <div className="page-grid"><section className="panel"><PanelTitle t="Jadwal kuliah" a={admin?'Admin dapat menambah jadwal':''}/>{admin&&<button className="primary" onClick={onAdd}>＋ Tambah jadwal</button>}{days.map(d=><div key={d} className="day-block"><h3>{d}</h3>{schedule.filter(s=>s.day===d).map(s=><div className="large-schedule" key={s.id}><div className="large-time">{s.start_time}<span>{s.end_time}</span></div><div><h3>{s.courses?.name}</h3><p>{s.lecturer||'Dosen belum diisi'} · {s.room||'Ruangan belum diisi'}</p></div></div>)}</div>)}</section></div>}
function Tasks({tasks,onOpen}){return <div className="page-grid"><section className="panel"><PanelTitle t="Tugas saya" a={`${tasks.length} tugas`}/>{tasks.map(t=><TaskRow t={t} open={()=>onOpen(t)} key={t.id}/>)}</section></div>}
function TaskRow({t,open}){const [lab,cl]=urgency(t.deadline,t.mine.status);return <button className="task-row" onClick={open}><div className={`priority-dot ${t.priority.toLowerCase()}`}/><div className="task-main"><strong>{t.title}</strong><span>{t.courses?.name||t.course}</span></div><div className="task-status"><span className={`badge ${cl}`}>{lab}</span><span>{fd(t.deadline)}</span></div><div className="status-mini">{t.mine.status==='Selesai'?'✓':`${t.mine.progress}%`}</div><div>›</div></button>}
function Calendar({tasks,schedule}){const [m,setM]=useState(new Date());const daysIn=new Date(m.getFullYear(),m.getMonth()+1,0).getDate();const offset=(new Date(m.getFullYear(),m.getMonth(),1).getDay()+6)%7;const cells=[...Array(offset).fill(null),...Array.from({length:daysIn},(_,i)=>i+1)];return <section className="panel calendar"><div className="calendar-head"><button onClick={()=>setM(new Date(m.getFullYear(),m.getMonth()-1,1))}>‹</button><h2>{new Intl.DateTimeFormat('id-ID',{month:'long',year:'numeric'}).format(m)}</h2><button onClick={()=>setM(new Date(m.getFullYear(),m.getMonth()+1,1))}>›</button></div><div className="weekdays">{['Sen','Sel','Rab','Kam','Jum','Sab','Min'].map(x=><b key={x}>{x}</b>)}</div><div className="calendar-grid">{cells.map((d,i)=>d?<div className="calendar-cell" key={i}><strong>{d}</strong>{(()=>{const dt=new Date(m.getFullYear(),m.getMonth(),d);const dn=dname(dt);const sc=schedule.filter(s=>s.day===dn);const iso=dt.toISOString().slice(0,10);const tc=tasks.filter(t=>t.deadline.startsWith(iso));return <>{sc.length>0&&<span className="cal-event class-event">{sc.length} kelas</span>}{tc.length>0&&<span className="cal-event task-event">{tc.length} tugas</span>}</>})()}</div>:<div className="calendar-cell empty-cell" key={i}/>)}</div></section>}
function Courses({courses,tasks,schedule,onOpen}){return <div className="course-layout"><section className="panel course-list">{courses.map(c=><div className="course-item" key={c.id}><span>{c.name.slice(0,2).toUpperCase()}</span><div><strong>{c.name}</strong><small>{tasks.filter(t=>t.course_id===c.id&&t.mine.status!=='Selesai').length} tugas belum selesai</small></div></div>)}</section></div>}
function Admin({courses,tasks,schedule,onTask,onSchedule}){return <div className="page-grid"><section className="stats"><Stat n={courses.length} l="Mata kuliah"/><Stat n={schedule.length} l="Jadwal"/><Stat n={tasks.length} l="Tugas"/></section><div className="two-panels"><section className="panel"><PanelTitle t="Kelola tugas" a="Admin"/><p className="muted">Admin dapat membuat tugas untuk seluruh mahasiswa, menentukan deadline, prioritas, link pengumpulan, dan mengunggah foto instruksi.</p><button className="primary" onClick={onTask}>＋ Tambah tugas</button></section><section className="panel"><PanelTitle t="Kelola jadwal" a="Admin"/><p className="muted">Tambahkan jadwal, dosen, dan ruangan. Jadwal akan terlihat oleh semua akun.</p><button className="primary" onClick={onSchedule}>＋ Tambah jadwal</button></section></div></div>}
function TaskDetail({task,mine,admin,onClose,update}){const [lab,cl]=urgency(task.deadline,mine.status);return <div className="modal-backdrop"><div className="modal detail-modal"><div className="modal-head"><div><span className={`badge ${cl}`}>{lab}</span><h2>{task.title}</h2><p>{task.courses?.name}</p></div><button className="close" onClick={onClose}>×</button></div><div className="detail-grid"><div><span>Deadline</span><strong>{fd(task.deadline)}</strong></div><div><span>Prioritas</span><strong>{task.priority}</strong></div><div><span>Status</span><select value={mine.status} onChange={e=>update({status:e.target.value,progress:e.target.value==='Selesai'?100:mine.progress})}><option>Belum mulai</option><option>Sedang dikerjakan</option><option>Selesai</option></select></div></div><div className="description">{task.description||'Tidak ada deskripsi tambahan.'}</div><label>Progress <b>{mine.progress}%</b><input type="range" min="0" max="100" value={mine.progress} onChange={e=>update({progress:+e.target.value,status:+e.target.value===100?'Selesai':'Sedang dikerjakan'})}/></label>{task.task_attachments?.length>0&&<div><div className="eyebrow">Instruksi tugas</div><div className="attachments">{task.task_attachments.map(a=><Attachment key={a.id} a={a}/>)}</div></div>}{task.submission_url&&<a className="primary full" href={task.submission_url} target="_blank" rel="noreferrer">Kumpulkan Tugas ↗</a>}</div>}
function Attachment({a}){const [url,setUrl]=useState(null);useEffect(()=>{(async()=>{const s=createClient();const {data}=await s.storage.from('task-instructions').createSignedUrl(a.path,3600);if(data)setUrl(data.signedUrl)})()},[a.path]);return url?<a href={url} target="_blank" rel="noreferrer"><img className="instruction-img" src={url} alt={a.file_name}/></a>:<div className="image-loading">Memuat gambar…</div>}
function TaskForm({courses,onClose,onSave}){return <div className="modal-backdrop"><form className="modal" onSubmit={onSave}><div className="modal-head"><div><div className="eyebrow">ADMIN</div><h2>Tambah Tugas</h2></div><button type="button" className="close" onClick={onClose}>×</button></div><label>Nama tugas<input name="title" required/></label><label>Mata kuliah<select name="course_id">{courses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Deskripsi / instruksi<textarea name="description"/></label><div className="two-col"><label>Deadline<input name="deadline" type="datetime-local" required/></label><label>Prioritas<select name="priority"><option>Rendah</option><option>Sedang</option><option>Tinggi</option></select></label></div><label>Link pengumpulan<input name="submission_url" type="url" placeholder="https://..."/></label><label>Foto instruksi tugas<input name="images" type="file" accept="image/*" multiple/><small className="muted">Gunakan gambar untuk screenshot atau instruksi tugas. Disarankan tiap file ≤ 6 MB.</small></label><button className="primary full">Simpan tugas</button></form></div>}
function ScheduleForm({courses,onClose,onSave}){return <div className="modal-backdrop"><form className="modal" onSubmit={onSave}><div className="modal-head"><div><div className="eyebrow">ADMIN</div><h2>Tambah Jadwal</h2></div><button type="button" className="close" onClick={onClose}>×</button></div><label>Mata kuliah<select name="course_id">{courses.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><div className="two-col"><label>Hari<select name="day">{days.map(d=><option key={d}>{d}</option>)}</select></label><label>Mulai<input name="start_time" type="time" required/></label></div><div className="two-col"><label>Selesai<input name="end_time" type="time" required/></label><label>Ruangan<input name="room"/></label></div><label>Dosen<input name="lecturer"/></label><button className="primary full">Simpan jadwal</button></form></div>}
function Stat({n,l}){return <div className="stat"><span className="stat-icon">●</span><div><strong>{n}</strong><small>{l}</small></div></div>}function PanelTitle({t,a}){return <div className="panel-title"><h3>{t}</h3><span>{a}</span></div>}function Empty({t}){return <div className="empty">{t}</div>}
